import groovy.json.JsonSlurper

echo "Hello from jenkins shared library jenkinsfile....."
//def pipelineParams= [:]
def test = new JsonSlurper().parseText '''
{"MY_NAME": "Jenkins name"}
'''

println test
   

myTemplate{ test }
