import groovy.json.JsonSlurper

echo "Hello from jenkins shared library jenkinsfile....."
def pipelineParams= [:]
myTemplate{ pipelineParams }

//def inputFile = new File('${WORKSPACE}/vars/config.json')
//def inputFile = new File(this.class.classLoader.getResourceLoader().loadGroovySource(this.class.name).toURI())
/*pipeline {
    agent any

    stages {
        
        stage('Test') {
            steps {
                echo 'Testing..'
                echo "${env.WORKSPACE}"
                script {
                    
                    def inputFile = new File("${env.WORKSPACE}/vars/config.json")
                //def inputJSON = new JsonSlurper().parse(inputFile)
                  //  Map parsedJson = new JsonSlurper().parse(inputFile)

                //println parsedJson

               String jsonString = '''{"menu": {
"id": "file",
"tools": {
"actions": [
{"id": "new", "title": "New File"},
{"id": "open", "title": "Open File"},
{"id": "close", "title": "Close File"}
],
"errors": []
}}}'''
JsonSlurper slurper = new JsonSlurper()
Map parsedJson = slurper.parseText(jsonString)
                    println parsedJson
                //myTemplate{ jsonString }
                    //myTemplate{ pipelineParams }
                }
                
            }
        }
        
    }
}

*/
   

               






//@Library('MyJenkins_Library') _
//def jsonSlurper = new JsonSlurper()

//File fl = new File('${WORKSPACE}/jenkinsConfig.json')

// parse(File file) method is available since 2.2.0
//def obj = jsonSlurper.parse(fl)
//echo "******"
//echo "OBJ:: $obj"

